### ISSUE TITLE
Move Postgres to Cindervolume or similar

### ISSUE THREAD

**Issue by andersla** [phnmnl/KubeNow-plugin#22]
Put postgres data on a Cindervolume or similar to improve postgres speed

**Comment by sneumann** [comment]
First we need to request a second volume in the terraform part, say 5GB,

Then we define a PV as in pv_cinder.yaml that has to go into the helm chart of the 
postgres service:
```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "cinder-jenkins" 
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - "ReadWriteOnce"
  cinder: 
    fsType: "ext4" 
volumeID: "a2f...48173e"
```
The volumeID must be passed on from Terraform.

K8S will make sure the physical mount will follow the postgres pod in case it is moved around.
